import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(require.resolve('playwright', { paths: [process.env.CODEX_NODE_MODULES || 'C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules'] }));
const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('http://127.0.0.1:5180/tests/subway-preview.html');
  const input = page.getByRole('textbox', { name: '정거장 이름 입력' });
  await input.waitFor();
  await page.screenshot({ path: 'tests/subway-desktop.png', fullPage: true });
  await input.fill('오타');
  await input.press('Enter');
  await page.getByText('정거장 이름을 다시 확인해주세요.').waitFor();
  const blocked = await input.evaluate((element) => ['paste', 'drop'].map((type) => !element.dispatchEvent(new Event(type, { bubbles: true, cancelable: true }))));
  assert.deepEqual(blocked, [true, true]);
  assert.equal(await page.locator('.metro-word').evaluate((e) => getComputedStyle(e).userSelect), 'none');
  const names = ['진접','오남','별내별가람','불암산','상계','노원','창동','쌍문','수유','미아','미아사거리','길음','성신여대입구','한성대입구','혜화','동대문'];
  for (const name of names) { await input.fill(name); await input.press('Enter'); }
  await page.getByText('기록이 선생님께 제출되었습니다.').waitFor();
  await page.screenshot({ path: 'tests/subway-finish.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.reload();
  await input.waitFor();
  await page.screenshot({ path: 'tests/subway-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.goto('http://127.0.0.1:5180/tests/subway-preview.html?progress=15&fail=1');
  await page.locator('.metro-word').filter({ hasText: '동대문' }).waitFor();
  await input.fill('동대문');
  await input.press('Enter');
  await page.getByText('테스트 저장 실패').waitFor();
  await page.getByRole('button', { name: '기록 저장 다시 시도' }).click();
  await page.getByText('기록이 선생님께 제출되었습니다.').waitFor();
  await page.goto('http://127.0.0.1:5180/tests/subway-preview.html?progress=4&expired=1');
  await page.getByText('운행 시간이 종료됐어요').waitFor();
  await page.getByText('기록이 선생님께 제출되었습니다.').waitFor();
  assert.deepEqual(errors, []);
  await page.goto('http://127.0.0.1:5180/tests/subway-preview.html?memory=1');
  await page.getByRole('dialog', { name: '지금 외우세요!' }).waitFor();
  await page.screenshot({ path: 'tests/subway-memorize-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: 'tests/subway-memorize-desktop.png', fullPage: true });
  assert.equal(await input.isDisabled(), true);
  await page.locator('.metro-memory-route').waitFor();
  await page.getByRole('button', { name: '초성 힌트 +3초' }).waitFor({ timeout: 20000 });
  assert.equal(await page.getByRole('dialog').count(), 0);
  assert.equal(await page.locator('.metro-word').textContent(), '01??');
  await page.getByRole('button', { name: '초성 힌트 +3초' }).click();
  assert.equal(await page.locator('.metro-word').textContent(), '01ㅈㅈ');
  await page.getByRole('button', { name: '정답 보기 +5초' }).click();
  assert.equal(await page.locator('.metro-word').textContent(), '01진접');
  await page.getByText('힌트 가산 8초').waitFor();
  await input.fill('진접'); await input.press('Enter');
  assert.equal(await page.locator('.metro-word').textContent(), '02??');
  await page.screenshot({ path: 'tests/subway-memory.png', fullPage: true });
  await page.goto('http://127.0.0.1:5180/tests/subway-preview.html?leaderboard=1');
  await page.getByText('노원 도착', { exact: true }).waitFor();
  await page.getByText('6 / 16개 · 38%', { exact: true }).waitFor();
  await page.getByText('도착 기록 없음', { exact: true }).waitFor();
  await page.screenshot({ path: 'tests/subway-leaderboard.png', fullPage: true });
  await page.getByText('미입장 학생 이름', { exact: true }).waitFor();
  await page.getByText('입장 1 / 2명 · 미입장 1명', { exact: true }).waitFor();
  await page.goto('http://127.0.0.1:5180/tests/subway-preview.html?recall=1');
  await input.fill('오이도'); await input.press('Enter');
  await page.getByText('오이도 정답!', { exact: true }).waitFor();
  await input.fill('오이도'); await input.press('Enter');
  await page.getByText('이미 입력한 역이에요.', { exact: true }).waitFor();
  await input.fill('강남'); await input.press('Enter');
  await page.getByText('4호선 역 이름을 확인해주세요.', { exact: true }).waitFor();
  assert.equal(await page.locator('.metro-recall-map .found').count(), 1);
  assert.equal(await page.evaluate(() => window.subwayTestSubmissions || 0), 0);
  await page.screenshot({ path: 'tests/subway-recall-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'tests/subway-recall-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.goto('http://127.0.0.1:5180/tests/subway-preview.html?recall=1&progress=50');
  assert.equal(await page.locator('.metro-recall-map .found').count(), 50);
  await input.fill('오이도'); await input.press('Enter');
  await page.getByText('기록이 선생님께 제출되었습니다.').waitFor();
  assert.equal(await page.evaluate(() => window.subwayTestSubmissions), 1);
  await page.goto('http://127.0.0.1:5180/tests/subway-preview.html?recall=1&progress=4&expired=1');
  await page.getByText('4개 정답', { exact: true }).waitFor();
  await page.getByText('기록이 선생님께 제출되었습니다.').waitFor();
  assert.deepEqual(errors, []);
  console.log('Desktop/mobile, typo, paste/drop, select-none, completion, restoration, retry and timeout passed.');
  await page.setViewportSize({ width: 1366, height: 768 });
  await page.goto('http://127.0.0.1:5180/tests/subway-preview.html?recall=1&study=1');
  await page.getByText('역 이름을 기억하세요!', { exact: true }).waitFor();
  assert.equal(await page.locator('.metro-study-groups li').count(), 51);
  assert.equal(await input.count(), 0);
  assert.equal(await page.evaluate(() => window.subwayTestSubmissions || 0), 0);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: 'tests/subway-study-chromebook.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: 'tests/subway-study-mobile.png', fullPage: true });
  await input.waitFor({ timeout: 20000 });
  await page.getByText('기억나는 역 이름을 입력하세요', { exact: true }).waitFor();
  assert.equal(await page.locator('.metro-study-groups').count(), 0);
  assert.equal(await input.evaluate(el => el === document.activeElement), true);
  assert.deepEqual(errors, []);
} finally { await browser.close(); }
