export const COSMETIC_ITEMS = [
  {
    id: 'glow_teal',
    name: '청록빛 오라',
    description: '점수판에서 이름 주변에 시원한 청록빛이 은은하게 빛납니다.',
    price: 80,
    previewClass: 'cosmetic-preview cosmetic-preview-teal',
    leaderboardClass: 'cosmetic-row cosmetic-row-teal',
    badgeClass: 'cosmetic-badge cosmetic-badge-teal',
    effectClass: 'cosmetic-effect-aura',
  },
  {
    id: 'border_forest',
    name: '숲속 테두리',
    description: '초록 숲길처럼 차분한 테두리로 기록을 강조합니다.',
    price: 100,
    previewClass: 'cosmetic-preview cosmetic-preview-forest',
    leaderboardClass: 'cosmetic-row cosmetic-row-forest',
    badgeClass: 'cosmetic-badge cosmetic-badge-forest',
    effectClass: 'cosmetic-effect-forest',
  },
  {
    id: 'badge_summer',
    name: '여름 별 배지',
    description: '닉네임 옆에 여름 별처럼 반짝이는 배지 느낌을 더합니다.',
    price: 120,
    previewClass: 'cosmetic-preview cosmetic-preview-summer',
    leaderboardClass: 'cosmetic-row cosmetic-row-summer',
    badgeClass: 'cosmetic-badge cosmetic-badge-summer',
    effectClass: 'cosmetic-effect-sun',
  },
  {
    id: 'shine_wave',
    name: '파도 반짝임',
    description: '파도처럼 푸른빛이 흐르는 시원한 강조 효과입니다.',
    price: 150,
    previewClass: 'cosmetic-preview cosmetic-preview-wave',
    leaderboardClass: 'cosmetic-row cosmetic-row-wave',
    badgeClass: 'cosmetic-badge cosmetic-badge-wave',
    effectClass: 'cosmetic-effect-wave',
  },
  {
    id: 'title_mvp',
    name: 'MVP 왕관',
    description: '이달의 MVP에게 어울리는 황금 왕관 칭호입니다. 점수판에서 가장 화려하게 빛납니다.',
    price: 9999,
    category: 'title',
    previewClass: 'cosmetic-preview cosmetic-preview-title-mvp',
    leaderboardClass: 'cosmetic-row cosmetic-row-title-mvp',
    badgeClass: 'cosmetic-badge cosmetic-badge-title-mvp',
    effectClass: 'cosmetic-effect-title-mvp',
  },
  {
    id: 'title_quiz_king',
    name: '퀴즈왕',
    description: '퀴즈를 가장 많이 맞힌 학생에게 주는 번뜩이는 지식의 칭호입니다.',
    price: 9999,
    category: 'title',
    previewClass: 'cosmetic-preview cosmetic-preview-title-quiz',
    leaderboardClass: 'cosmetic-row cosmetic-row-title-quiz',
    badgeClass: 'cosmetic-badge cosmetic-badge-title-quiz',
    effectClass: 'cosmetic-effect-title-quiz',
  },
  {
    id: 'title_practice_king',
    name: '꾸준왕',
    description: '로그인 자유연습을 성실하게 이어간 학생에게 주는 성장의 칭호입니다.',
    price: 9999,
    category: 'title',
    previewClass: 'cosmetic-preview cosmetic-preview-title-practice',
    leaderboardClass: 'cosmetic-row cosmetic-row-title-practice',
    badgeClass: 'cosmetic-badge cosmetic-badge-title-practice',
    effectClass: 'cosmetic-effect-title-practice',
  },
  {
    id: 'title_speed_king',
    name: '속도왕',
    description: '가장 빠른 CPM을 보여준 학생에게 주는 전광석화 칭호입니다.',
    price: 9999,
    category: 'title',
    previewClass: 'cosmetic-preview cosmetic-preview-title-speed',
    leaderboardClass: 'cosmetic-row cosmetic-row-title-speed',
    badgeClass: 'cosmetic-badge cosmetic-badge-title-speed',
    effectClass: 'cosmetic-effect-title-speed',
  },
];

export function getCosmeticById(cosmeticId) {
  return COSMETIC_ITEMS.find((item) => item.id === cosmeticId) || null;
}
