export const FIRESTORE_PATHS = {
  rooms: 'typing_rooms',
  scores: 'typing_scores',
  announcements: 'typing_announcements',
  quizzes: 'typing_quizzes',
  words: 'typing_words',
  classes: 'typing_classes',
  classStudents: 'typing_class_students',
  classRoster: 'typing_class_roster',
  studentSessions: 'typing_student_sessions',
  roomPresence: 'typing_room_presence',
  hallOfFame: 'typing_hall_of_fame',
  shopItems: 'typing_shop_items',
  shopPurchases: 'typing_shop_purchases',
  practiceRecords: 'typing_practice_records',
};
