export const KOREAN_WORDS = [
            // 기본 학교생활 & 일상
            "학교", "선생님", "교과서", "칠판", "체육대회", "수학여행", "중간고사", "기말고사", "쉬는시간", "점심시간",
            "도서관", "과학실", "미술실", "음악실", "동아리", "급식", "친구", "우정", "추억", "졸업식", "정보교과",
            "수행평가", "방학식", "개학식", "학급회의", "동아리활동", "학생회장", "교장선생님", "담임선생님", "진로상담", 
            "가정통신문", "알림장", "조회시간", "종례시간", "야간자율학습", "교복", "체육복", "풍양중학교",

            // 정보/컴퓨터 교과 특화 (선생님 맞춤형)
            "인공지능", "파이썬", "리액트", "자바스크립트", "코딩", "알고리즘", "소프트웨어", "하드웨어", "메인보드", 
            "그래픽카드", "스마트폰", "데이터베이스", "네트워크", "운영체제", "프로그래밍", "웹개발", "클라우드", "서버", 
            "키보드", "마우스", "모니터", "머신러닝", "딥러닝", "프롬프트", "메타버스", "사물인터넷", "가상현실", 
            "증강현실", "프론트엔드", "백엔드", "디버깅", "오류", "버그", "해킹", "정보보안", "인터넷",

            // 중학생 트렌드 & 음식
            "마라탕", "탕후루", "떡볶이", "돈까스", "치킨", "피자", "햄버거", "아이스크림", "콜라", "사이다",
            "아메리카노", "에이드", "소떡소떡", "버블티", "코인노래방", "네컷사진", "웹툰", "유튜브", "알고리즘의 선택",
            "완전 럭키비키잖아", "폼미쳤다", "중요한 것은 꺾이지 않는 마음", "오운완", "알잘딱깔센", "취향존중", "벼락치기",

            // 짧은 명언 및 속담
            "푸른 하늘 은하수 하얀 쪽배에", "계수나무 한 나무 토끼 한 마리", "남산 위에 저 소나무 철갑을 두른 듯", 
            "동해 물과 백두산이 마르고 닳도록", "배움에는 끝이 없다", "연습은 완벽을 만든다", "오늘의 노력이 내일의 실력", 
            "가는 말이 고와야 오는 말이 곱다", "시작이 반이다", "천 리 길도 한 걸음부터", "티끌 모아 태산", 
            "포기하지 않으면 실패는 없다", "시간은 금이다", "백지장도 맞들면 낫다", "아는 것이 힘이다",
            "바른 인성과 실력을 갖춘 인재", "꿈을 향해 도전하는 우리들", "별 헤는 밤 하늘을 우러러 한 점 부끄럼이 없기를",

            // 🌟 코딩 & 학교생활 관련 재미있는 긴 문장 (추가)
            "일찍 일어나는 새가 피곤하다",
            "맛있게 먹으면 0칼로리",
            "왜 안 돌아가지? 왜 돌아가지?",
            "세상에 완벽한 코드는 없다",
            "내 코드에 버그가 있을 리 없어",
            "컴퓨터는 거짓말을 하지 않는다",
            "백 번 듣는 것보다 한 번 코딩하는 것이 낫다",
            "Ctrl+C와 Ctrl+V는 나의 빛과 소금",
            "코딩의 완성은 디버깅이다",
            "에러 메시지를 두려워하지 말라",
            "오늘 피하면 내일은 두 배로 해야 한다",
            "에러가 발생했습니다 다시 시도해주세요",
            "코딩은 손으로 하는 것이 아니라 머리로 하는 것이다",
            "우리는 자랑스러운 풍양중학교 학생이다",

            // 🌿 여름 숲속 테마 & 정보 교과 확장 단어/문장
            "여름",
            "산바람",
            "계곡물",
            "숲길",
            "그늘",
            "파도",
            "소나기",
            "장마",
            "우산",
            "수박",
            "얼음물",
            "선풍기",
            "방학",
            "매미",
            "구름",
            "하늘",
            "햇살",
            "초록빛",
            "산책",
            "운동장",
            "정보실",
            "키보드",
            "마우스",
            "모니터",
            "알고리즘",
            "순서도",
            "변수",
            "함수",
            "반복문",
            "조건문",
            "디버깅",
            "자료구조",
            "인공지능",
            "네트워크",
            "데이터",
            "정보보안",
            "클라우드",
            "서버",
            "브라우저",
            "프로그래밍",
            "푸른 산바람이 교실 창문으로 들어온다",
            "시원한 계곡물 소리가 여름을 알려 준다",
            "초록빛 숲길을 걸으면 마음이 차분해진다",
            "정확한 타자는 빠른 속도보다 먼저 익혀야 한다",
            "오늘의 작은 연습이 내일의 실력이 된다",
            "실수해도 다시 도전하면 기록은 좋아진다",
            "키보드를 바르게 놓고 손가락 위치를 확인한다",
            "알고리즘은 문제를 해결하는 순서이다",
            "조건문은 상황에 따라 다른 명령을 실행한다",
            "반복문은 같은 일을 여러 번 처리할 때 사용한다",
            "디버깅은 오류를 찾고 고치는 과정이다",
            "정보보안은 나와 친구의 정보를 지키는 일이다",
            "좋은 프로그램은 사용자를 먼저 생각한다",
            "친구와 함께 배우면 어려운 문제도 쉬워진다",
            "차분하게 입력하면 오타가 줄어든다",
            "집중해서 읽고 정확하게 입력한다",
            "푸른 하늘 아래에서 새로운 기록에 도전한다",
            "여름 방학 전까지 꾸준히 연습한다",
            "빠르게 치는 것보다 정확하게 치는 것이 중요하다",
            "오늘도 풍양중학교 키보드 배틀에 도전한다"
        ];

export const ENGLISH_WORDS = [
            // Basic & School
            "apple", "banana", "school", "student", "teacher", "book", "desk", "chair", "notebook", "pencil",
            "library", "science", "music", "art", "history", "math", "english", "friend", "study", "learn",
            "classroom", "homework", "semester", "graduation", "uniform", "subject", "vocabulary", "grammar",

            // Emotion & Abstract
            "future", "dream", "success", "challenge", "passion", "effort", "courage", "wisdom", "health", "peace",
            "happy", "smile", "laugh", "love", "hope", "believe", "amazing", "awesome", "perfect", "great",

            // 🌟 CS / Tech / Coding (대폭 추가)
            "computer", "keyboard", "mouse", "internet", "coding", "software", "hardware", "network", "program",
            "python", "react", "javascript", "developer", "server", "database", "algorithm", "variable", "function",
            "artificial intelligence", "machine learning", "deep learning", "big data", "cloud computing",
            "front end", "back end", "full stack", "operating system", "protocol", "debug", "compiler", 
            "execution", "exception", "framework", "terminal", "console", "syntax", "object", "array", "string",

            // Proverbs & Famous Quotes
            "Time is gold", "No pain, no gain", "Knowledge is power", "Practice makes perfect", 
            "Where there is a will, there is a way", "Actions speak louder than words", 
            "Honesty is the best policy", "Rome was not built in a day", 
            "To be or not to be, that is the question", "I think, therefore I am", "Seize the day",
            "A rolling stone gathers no moss", "Better late than never", "Don't judge a book by its cover",

            // 🌟 Fun & Coding Quotes (추가)
            "The quick brown fox jumps over the lazy dog", 
            "Hello, World!", 
            "Show me the code.", 
            "Keep calm and write code.", 
            "Talk is cheap. Show me the code.", 
            "First, solve the problem. Then, write the code.", 
            "Make it work, make it right, make it fast.", 
            "Error 404 Not Found", 
            "I am not a bug, I am a feature.", 
            "May the Force be with you.", 
            "Just do it.", 
            "Never give up.",
            "Ctrl C and Ctrl V",

            // 🌿 Summer forest theme & computer class expansion
            "summer",
            "mountain",
            "valley",
            "forest",
            "breeze",
            "stream",
            "cloud",
            "sunlight",
            "shade",
            "waterfall",
            "ocean",
            "wave",
            "island",
            "hiking",
            "keyboard",
            "accuracy",
            "speed",
            "logic",
            "variable",
            "function",
            "loop",
            "condition",
            "debug",
            "database",
            "network",
            "security",
            "browser",
            "server",
            "client",
            "component",
            "state",
            "event",
            "render",
            "practice",
            "challenge",
            "teamwork",
            "focus",
            "progress",
            "record",
            "typing",
            "The cool mountain breeze enters the classroom.",
            "Green forests make the summer feel fresh.",
            "A small stream flows beside the mountain path.",
            "Practice every day and your typing will improve.",
            "Accuracy is more important than speed at first.",
            "Read the word carefully before you type.",
            "A good habit makes a strong programmer.",
            "Debugging helps us find and fix mistakes.",
            "A loop repeats the same task many times.",
            "A condition changes the path of a program.",
            "Data should be protected with care.",
            "Teamwork makes difficult problems easier.",
            "Focus on the screen and keep your rhythm.",
            "Every challenge can become a new record.",
            "The keyboard is a tool for clear thinking.",
            "A browser shows the web page to the user.",
            "A server sends data to the client.",
            "A component makes the screen easier to build.",
            "Small progress can become a big result.",
            "Keep calm and type with confidence."
        ];
